import React from "react";
import Sidebar from "@/components/dashboard/Layouts/Sidebar";
import Header from "@/components/dashboard/Layouts/Header";

export const metadata = {
  title: "AyoubSVT Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen showScren">
      <Sidebar />
      <div className="flex flex-col flex-1">
        <Header />
        {children}
      </div>
    </div>
  );
}
